### ISSUE TITLE
[Coverage] Project class

### ISSUE THREAD

**Issue by Jumaruba** [Jumaruba/jtimesched#23]
# Current Coverage 
![image](https://user-images.githubusercontent.com/33182421/200297171-24afe8dd-9607-4944-ab3e-42d0602bcd4c.png)

# Functions 
![image](https://user-images.githubusercontent.com/33182421/200297076-d5e038b8-0cc1-4759-ad21-8a9810723585.png)

**Comment by dianaamfr** [comment]
- [ ] toString
- [ ] pause
- [ ] getElapsedSeconds
- [ ] adjustSecondsToday
- [ ] start
- [ ] getSecondsOverall
- [ ] resetToday
- [ ] toggle
- [ ] getSecondsToday
- [ ] setScondsOverall
- [ ] setTitle
- [ ] setNotes
- [ ] setColor
- [ ] setChecked
- [ ] setTimeCreated
- [ ] setTimeStart
- [ ] setQuotaOverall
- [ ] setQuotaToday
